### ISSUE TITLE
Page d'accueil pour l'utilisateur connecté

### ISSUE THREAD

**Issue by Carole-PIGNA** [bahaa-tohami/EventApp_front#4]
- navbar : (logo,  Gestion des évènements, Mes notifications,  Mon profil, Déconnexion)
- Liste de tous les évènements **publics**, et évènements créés
- Calendrier en sticky sur le côté
- différents filtres sur les évènements
- footer

**Comment by bahaa-tohami** [comment]
![ecplzrieriozer](https://github.com/user-attachments/assets/3542bbf6-ff0f-40cf-be28-44ae1e6da5fc)

**Comment by Carole-PIGNA** [comment]
une autre issue va être ouverte pour les filtres
