### ISSUE TITLE
Page détails de l'évènement

### ISSUE THREAD

**Issue by Carole-PIGNA** [bahaa-tohami/EventApp_front#7]
-navbar
- Affiche un seul évènement avec toutes ses attributs (par récupération event_id)
- Ajouter un commentaire
- Ajouter une note
- inviter un utilisateur si je suis le proprietaire de l'evenement
- footer

**Comment by bahaa-tohami** [comment]
- afficher les participants invité

**Comment by Carole-PIGNA** [comment]
- si je suis le createur de l'evenement, afficher la liste des participants
